spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/authdb}
    username: ${DB_USERNAME:auth_db_user}
    password: ${DB_PASSWORD:change-me}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: off
  logging:
    level:
      org.springframework.security: TRACE
      org.springframework.security.authentication: TRACE
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET:YourJWTSecretKeyHereChangeIt}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION_MS:3600000} # 1 час в миллисекундах
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION_MS:86400000} # 24 часа в миллисекундах

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: ${SERVER_PORT:8080}